### ISSUE TITLE
Remove the Releases from Projects

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/test#3]
Milestones already track what is marked against a release, as mile stones are the releases, so we can remove the project "Releases" from the project tab.

**Comment by ShyamsundarR** [comment]
Marking done...

**Comment by nigelbabu** [comment]
This patch will update or fix this issue: https://gerrit-stage.rht.gluster.org/16453
Commit Message: This is a test commit that fixes things

**Comment by gluster-ant** [comment]
This patch will update or fix this issue: https://gerrit-stage.rht.gluster.org/16453
Commit Message: This is a test commit that fixes things
